=== git-maniam/M6E/browser/components/sessionstore/session.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "array",
      "items": {
        "type": ["string", "integer"]
      }
    },
    "windows": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/openWindow"
      }
    },
    "_closedWindows": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/closedWindow"
      }
    },
    "savedGroups": {
      "type": "array"
    },
    "session": {
      "type": "object",
      "properties": {
        "lastUpdate": {
          "type": "integer"
        },
        "startTime": {
          "type": "integer"
        },
        "recentCrashes": {
          "type": "integer"
        }
      }
    },
    "global": {
      "type": "object"
    },
    "cookies": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cookie"
      }
    },
    "browserConsole": {
      "type": "boolean"
    },
    "browserToolbox": {
      "type": "boolean"
    },
    "selectedWindow": {
      "type": "integer"
    },
    "maxSplitViewId": {
      "type": "integer"
    }
  },
  "required": ["version", "windows"],
  "definitions": {
    "cookie": {
      "type": "object",
      "properties": {
        "host": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "secure": {
          "type": "boolean"
        },
        "httponly": {
          "type": "boolean"
        },
        "expiry": {
          "type": "integer"
        },
        "originAttributes": {
          "type": "object",
          "properties": {
            "firstPartyDomain": {
              "type": "string"
            },
            "geckoViewSessionContextId": {
              "type": "string"
            },
            "partitionKey": {
              "type": "string"
            },
            "privateBrowsingId": {
              "type": "integer"
            },
            "userContextId": {
              "type": "integer"
            }
          }
        },
        "sameSite": {
          "type": "integer"
        },
        "schemeMap": {
          "type": "integer"
        }
      },
      "required": []
    },
    "sidebar": {
      "type": "object",
      "properties": {
        "command": {
          "type": ["null", "string"]
        },
        "panelOpen": {
          "type": "boolean"
        },
        "panelWidth": {
          "type": ["null", "number"]
        },
        "userLauncherVisible": {
          "type": "boolean"
        },
        "launcherExpanded": {
          "type": "boolean"
        },
        "launcherWidth": {
          "type": ["null", "number"]
        }
      },
      "required": []
    },
    "window": {
      "type": "object",
      "properties": {
        "extData": {
          "type": "object"
        },
        "sidebar": {
          "$ref": "#/definitions/sidebar"
        },
        "selected": {
          "type": "integer"
        },
        "splitViews": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/splitview"
          }
        },
        "title": {
          "type": "string"
        },
        "tabs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/tab"
          }
        },
        "_closedTabs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/closedTab"
          }
        },
        "_lastClosedTabGroupCount": {
          "type": "integer"
        },
        "args": {
          "$comment": "Introduced Firefox 156, bug 2066315",
          "description": "Arguments to supply to nsIWindowWatcher.openWindow in order to restore a window's previous state",
          "type": "object",
          "properties": {
            "web-extension-popup-window": {
              "description": "Popup window opened by WebExtensions",
              "type": "boolean"
            },
            "chromeless-window": {
              "description": "Window with minimal chrome UI",
              "type": "boolean"
            }
          }
        },
        "chromeFlags": {
          "$comment": "Introduced Firefox 99, bug 1728800",
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "hidden": {
          "$comment": "Removed Firefox 156, bug 2065228",
          "deprecated": true,
          "type": "string"
        },
        "isPopup": {
          "type": "boolean"
        },
        "screenX": {
          "type": "integer"
        },
        "screenY": {
          "type": "integer"
        },
        "sizemode": {
          "type": "string",
          "enum": ["normal", "maximized", "minimized", "fullscreen"]
        },
        "sizemodeBeforeMinimized": {
          "type": "string",
          "enum": ["normal", "maximized", "minimized", "fullscreen"]
        },
        "width": {
          "type": "integer"
        },
        "zIndex": {
          "type": "integer"
        },
        "workspaceID": {
          "type": ["null", "string"]
        }
      },
      "required": ["tabs"]
    },
    "openWindow": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/window"
        }
      ],
      "properties": {
        "__lastSessionWindowID": {
          "type": "string"
        },
        "busy": {
          "type": "boolean"
        }
      },
      "required": [],
      "additionalProperties": true
    },
    "closedWindow": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/window"
        },
        {
          "type": "object",
          "properties": {
            "closedAt": {
              "type": "integer"
            },
            "closedId": {
              "type": "integer"
            }
          }
        }
      ],
      "required": ["closedAt", "closedId"],
      "additionalProperties": false
    },
    "splitview": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "numberOfTabs": {
          "type": "integer"
        }
      },
      "required": ["id", "numberOfTabs"]
    },
    "tab": {
      "type": "object",
      "properties": {
        "entries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/entry"
          }
        },
        "removeAfterRestore": {
          "type": "boolean"
        },
        "lastAccessed": {
          "type": "integer"
        },
        "hidden": {
          "type": "boolean"
        },
        "searchMode": {
          "type": "null"
        },
        "userContextId": {
          "type": "integer"
        },
        "attributes": {
          "type": "object"
        },
        "index": {
          "type": "integer"
        },
        "requestedIndex": {
          "type": "integer"
        },
        "image": {
          "type": ["null", "string"]
        },
        "storage": {
          "type": "object",
          "additionalProperties": {
            "type": "object"
          }
        },
        "canonicalUrl": {
          "type": "string"
        }
      },
      "required": [
        "entries",
        "lastAccessed",
        "hidden",
        "userContextId",
        "index"
      ]
    },
    "openTab": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/tab"
        }
      ]
    },
    "closedTab": {
      "type": "object",
      "properties": {
        "state": {
          "$ref": "#/definitions/tab"
        },
        "closedInGroup": {
          "type": "boolean"
        },
        "removeAfterRestore": {},
        "permanentKey": {
          "type": "object"
        },
        "title": {
          "type": "string"
        },
        "image": {
          "type": ["null", "string"]
        },
        "pos": {
          "type": "integer"
        },
        "closedAt": {
          "type": "integer"
        },
        "closedId": {
          "type": "integer"
        },
        "sourceWindowId": {
          "type": "string"
        }
      },
      "required": [
        "state",
        "title",
        "pos",
        "closedAt",
        "sourceWindowId",
        "closedId"
      ]
    },
    "entry": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "subframe": {
          "type": "boolean"
        },
        "persist": {
          "type": "boolean"
        },
        "principalToInherit_base64": {
          "type": "string"
        },
        "scrollRestorationIsManual": {
          "type": "boolean"
        },
        "hasUserInteraction": {
          "type": "boolean"
        },
        "triggeringPrincipal_base64": {
          "type": "string"
        },
        "resultPrincipalURI": {
          "type": ["null", "string"]
        },
        "scroll": {
          "type": "string"
        },
        "presState": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/presStateItem"
          }
        },
        "loadReplace": {
          "type": "boolean"
        },
        "loadReplace2": {
          "type": "boolean"
        },
        "csp": {
          "type": "string"
        },
        "contentType": {
          "type": "string"
        },
        "cacheKey": {
          "type": "integer"
        },
        "ID": {
          "type": "integer"
        },
        "srcdocData": {
          "type": "string"
        },
        "isSrcdocEntry": {
          "type": "boolean"
        },
        "baseURI": {
          "type": "string"
        },
        "docIdentifier": {
          "type": "integer"
        },
        "structuredCloneState": {
          "type": "string"
        },
        "structuredCloneVersion": {
          "type": "integer"
        },
        "docshellUUID": {
          "type": "string"
        },
        "referrerInfo": {
          "type": "string"
        },
        "originalURI": {
          "type": "string"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/entry"
          }
        },
        "policyContainer": {
          "type": "string"
        },
        "transient": {
          "type": "boolean"
        },
        "navigationKey": {
          "type": "string"
        },
        "navigationId": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": ["url", "title", "hasUserInteraction"]
    },
    "presStateItem": {
      "type": "object",
      "properties": {
        "stateKey": {
          "type": "string"
        },
        "scroll": {
          "type": "string"
        }
      }
    }
  }
}

=== git-maniam/M6E/browser/components/sessionstore/test/unit/data/sessionstore_complete.json
{
  "version": ["sessionrestore", 1],
  "windows": [
    {
      "tabs": [
        {
          "entries": [
            {
              "url": "about:home",
              "title": "New Tab",
              "cacheKey": 0,
              "ID": 889527166,
              "docshellUUID": "{1c51a53b-d2b5-4484-8deb-aef7bd44abc4}",
              "resultPrincipalURI": null,
              "principalToInherit_base64": "{\"0\":{\"0\":\"moz-nullprincipal:{6ec4bec4-5873-4b33-b269-be6653e318d8}\"}}",
              "hasUserInteraction": true,
              "triggeringPrincipal_base64": "{\"3\":{}}",
              "docIdentifier": 12,
              "transient": false,
              "navigationKey": "{d0185d51-bd9f-4f90-afb2-f40547ac08a8}",
              "navigationId": "{08e9abae-27f4-4cbb-8eb6-1524776e7327}"
            },
            {
              "url": "about:mozilla",
              "title": "The Book of Mozilla, 6:27",
              "cacheKey": 0,
              "ID": 889527167,
              "docshellUUID": "{1c51a53b-d2b5-4484-8deb-aef7bd44abc4}",
              "resultPrincipalURI": null,
              "principalToInherit_base64": "{\"0\":{\"0\":\"moz-nullprincipal:{b5d58330-101d-4601-9291-6435ebcb854e}\"}}",
              "hasUserInteraction": true,
              "triggeringPrincipal_base64": "{\"3\":{}}",
              "docIdentifier": 13,
              "transient": false,
              "navigationKey": "{e546bd8d-4813-4a8a-8e90-0cdde6b5ab72}",
              "navigationId": "{7fd8f06e-2863-4f78-85f4-a4684c635086}"
            }
          ],
          "lastAccessed": 1770416063211,
          "hidden": false,
          "groupId": "1770415115529-1",
          "searchMode": null,
          "userContextId": 0,
          "attributes": {},
          "index": 2,
          "requestedIndex": 0,
          "image": null
        },
        {
          "entries": [
            {
              "url": "about:newtab",
              "title": "New Tab",
              "cacheKey": 0,
              "ID": 889527170,
              "docshellUUID": "{739fd540-1ff5-4d46-8e55-896b64d6cfb3}",
              "resultPrincipalURI": null,
              "hasUserInteraction": true,
              "triggeringPrincipal_base64": "{\"3\":{}}",
              "docIdentifier": 14,
              "transient": false,
              "navigationKey": "{c3718cd7-fac1-4ca7-b728-73b028e8e26a}",
              "navigationId": "{b0b9cd99-3b46-4b98-b032-2d9ab1d649c0}"
            },
            {
              "url": "about:support",
              "title": "Troubleshooting Information",
              "cacheKey": 0,
              "ID": 889527171,
              "docshellUUID": "{739fd540-1ff5-4d46-8e55-896b64d6cfb3}",
              "resultPrincipalURI": null,
              "principalToInherit_base64": "{\"0\":{\"0\":\"moz-nullprincipal:{675de4b7-6fd5-47d4-a538-50bbcdca4c6c}\"}}",
              "hasUserInteraction": true,
              "triggeringPrincipal_base64": "{\"3\":{}}",
              "docIdentifier": 15,
              "transient": false,
              "navigationKey": "{f8decd0b-ac89-4e55-892e-3e8ed627ba0e}",
              "navigationId": "{ad8b07d9-29bf-4281-806a-c3534fc58d84}"
            },
            {
              "url": "about:preferences",
              "title": "Settings",
              "cacheKey": 0,
              "ID": 889527172,
              "docshellUUID": "{739fd540-1ff5-4d46-8e55-896b64d6cfb3}",
              "originalURI": "about:preferences",
              "resultPrincipalURI": null,
              "principalToInherit_base64": "{\"0\":{\"0\":\"moz-nullprincipal:{a6850bcd-5678-4594-9311-0affec22d009}\"}}",
              "hasUserInteraction": true,
              "triggeringPrincipal_base64": "{\"3\":{}}",
              "docIdentifier": 16,
              "structuredCloneState": "AgAAAAAA8f8LAACABAD//3BhbmVHZW5lcmFsAAAAAAA=",
              "structuredCloneVersion": 8,
              "children": [
                {
                  "url": "about:blank",
                  "title": "about:blank",
                  "cacheKey": 0,
                  "ID": 889527173,
                  "docshellUUID": "{5cdf1a82-9508-4a80-8884-312cb35c4b5a}",
                  "resultPrincipalURI": null,
                  "hasUserInteraction": true,
                  "triggeringPrincipal_base64": "{\"3\":{}}",
                  "policyContainer": "ydqGXsPXSqGicQ9XHwE8MAAAAAAAAAAAwAAAAAAAAEYAAAABAQnZ7Rrl1EAEv+Anzrkj2awdYyAIbJdIrqUcFuLaoPT2AeDaHXAvexHTjNAAYLD8FKOSBzpUbXhPMJE6uHGBMgjGAAAAAAVhYm91dAAAAAtwcmVmZXJlbmNlcwAAAAAACHsiMyI6e319AAAAAQAAAI8AZABlAGYAYQB1AGwAdAAtAHMAcgBjACAAYwBoAHIAbwBtAGUAOgA7ACAAaQBtAGcALQBzAHIAYwAgAGMAaAByAG8AbQBlADoAIABtAG8AegAtAGkAYwBvAG4AOgAgAG0AbwB6AC0AcgBlAG0AbwB0AGUALQBpAG0AYQBnAGUAOgAgAGgAdAB0AHAAcwA6ACAAYgBsAG8AYgA6ACAAZABhAHQAYQA6ADsAIABzAHQAeQBsAGUALQBzAHIAYwAgAGMAaAByAG8AbQBlADoAIABkAGEAdABhADoAIAAnAHUAbgBzAGEAZgBlAC0AaQBuAGwAaQBuAGUAJwA7ACAAbwBiAGoAZQBjAHQALQBzAHIAYwAgACcAbgBvAG4AZQAnAAEAAUgS/zIb/0I7l/xApWltrSJIEv8yG/9CO5f8QKVpba0iAAAAAQAA",
                  "docIdentifier": 17,
                  "transient": true,
                  "navigationKey": "{d292a0e0-a212-4147-a523-7196c1d82c09}",
                  "navigationId": "{72db572a-c072-4aa9-b282-e22fdb01150d}"
                },
                {
                  "url": "about:blank",
                  "title": "about:blank",
                  "cacheKey": 0,
                  "ID": 20,
                  "docshellUUID": "{99483b7c-4429-4610-970d-8e43b680cda6}",
                  "resultPrincipalURI": null,
                  "hasUserInteraction": true,
                  "triggeringPrincipal_base64": "{\"3\":{}}",
                  "policyContainer": "ydqGXsPXSqGicQ9XHwE8MAAAAAAAAAAAwAAAAAAAAEYAAAABAQnZ7Rrl1EAEv+Anzrkj2awdYyAIbJdIrqUcFuLaoPT2AeDaHXAvexHTjNAAYLD8FKOSBzpUbXhPMJE6uHGBMgjGAAAAAAVhYm91dAAAAAtwcmVmZXJlbmNlcwAAAAAACHsiMyI6e319AAAAAQAAAI8AZABlAGYAYQB1AGwAdAAtAHMAcgBjACAAYwBoAHIAbwBtAGUAOgA7ACAAaQBtAGcALQBzAHIAYwAgAGMAaAByAG8AbQBlADoAIABtAG8AegAtAGkAYwBvAG4AOgAgAG0AbwB6AC0AcgBlAG0AbwB0AGUALQBpAG0AYQBnAGUAOgAgAGgAdAB0AHAAcwA6ACAAYgBsAG8AYgA6ACAAZABhAHQAYQA6ADsAIABzAHQAeQBsAGUALQBzAHIAYwAgAGMAaAByAG8AbQBlADoAIABkAGEAdABhADoAIAAnAHUAbgBzAGEAZgBlAC0AaQBuAGwAaQBuAGUAJwA7ACAAbwBiAGoAZQBjAHQALQBzAHIAYwAgACcAbgBvAG4AZQAnAAEAAUgS/zIb/0I7l/xApWltrSJIEv8yG/9CO5f8QKVpba0iAAAAAQAA",
                  "docIdentifier": 22,
                  "transient": true,
                  "navigationKey": "{6dfc5997-9767-471e-a092-3d3cb72d5c18}",
                  "navigationId": "{949e9fde-2b4d-4588-8bfe-807a46c38f02}"
                }
              ],
              "transient": false,
              "navigationKey": "{f8241c63-5204-446f-82f4-9a200b7a57eb}",
              "navigationId": "{86153ed4-da40-4d2a-8017-8268fc40158f}"
            }
          ],
          "lastAccessed": 1770416070546,
          "hidden": false,
          "splitViewId": 1,
          "searchMode": null,
          "userContextId": 0,
          "attributes": {},
          "index": 3,
          "requestedIndex": 0,
          "formdata": {
            "url": "about:preferences",
            "id": {
              "searchInput": {
                "state": "",
                "value": ""
              },
              "browserRestoreSession": {
                "state": "on",
                "value": "on"
              },
              "windowsLaunchOnLogin": {
                "state": "on",
                "value": "on"
              },
              "alwaysCheckDefault": {
                "state": "on",
                "value": "on"
              },
              "linkTargeting": {
                "state": "on",
                "value": "on"
              },
              "switchToNewTabs": {
                "state": "on",
                "value": "on"
              },
              "openAppLinksNextToActiveTab": {
                "state": "on",
                "value": "on"
              },
              "warnOpenMany": {
                "state": "on",
                "value": "on"
              },
              "ctrlTabRecentlyUsedOrder": {
                "state": "on",
                "value": "on"
              },
              "tabPreviewShowThumbnails": {
                "state": "on",
                "value": "on"
              },
              "tabGroupSuggestions": {
                "state": "on",
                "value": "on"
              },
              "showTabsInTaskbar": {
                "state": "on",
                "value": "on"
              },
              "browserContainersCheckbox": {
                "state": "on",
                "value": "on"
              },
              "warnCloseMultiple": {
                "state": "on",
                "value": "on"
              },
              "warnOnQuitKey": {
                "state": "on",
                "value": "on"
              },
              "browserLayoutRadioGroup": {
                "state": "false",
                "value": "false"
              },
              "web-appearance-chooser": {
                "state": "auto",
                "value": "auto"
              },
              "contrastControlSettings": {
                "state": "1",
                "value": "1"
              },
              "contrastSettingsAuto": {
                "state": "0",
                "value": "0"
              },
              "contrastSettingsOff": {
                "state": "1",
                "value": "1"
              },
              "contrastSettingsOn": {
                "state": "2",
                "value": "2"
              },
              "defaultZoom": {
                "state": "100",
                "value": "100"
              },
              "zoomText": {
                "state": "on",
                "value": "on"
              },
              "chooseFolder": {
                "state": "/home/sfoster/Downloads",
                "value": "/home/sfoster/Downloads"
              },
              "alwaysAsk": {
                "state": "on",
